export interface UniverseDefinitionItem {
  id: string;
  date: string;
  originalDate?: string;
  service: string;
  region: "HKG" | "LDN" | "SGP";
  submittedBy: string;
  canUploadSUD: boolean;
}

export const mockUniverseData: UniverseDefinitionItem[] = [
  {
    id: "1",
    date: "Latest",
    service: "equity_vanilla_option",
    region: "HKG",
    submittedBy: "Theodore Duncan",
    canUploadSUD: true,
  },
  {
    id: "2",
    date: "Latest",
    service: "equity_barrier_option",
    region: "LDN",
    submittedBy: "Samira Khan",
    canUploadSUD: true,
  },
  {
    id: "3",
    date: "Latest",
    service: "equity_forward_ndf",
    region: "SGP",
    submittedBy: "Declan O'Connell",
    canUploadSUD: true,
  },
  {
    id: "4",
    date: "15/12/2025 03:17 PM",
    service: "equity_forward",
    region: "LDN",
    submittedBy: "Zoya Kapoor",
    canUploadSUD: false,
  },
  {
    id: "5",
    date: "15/12/2025 03:17 PM",
    service: "equity_swap_ldn",
    region: "SGP",
    submittedBy: "Jasper Klein",
    canUploadSUD: false,
  },
  {
    id: "6",
    date: "15/12/2025 03:17 PM",
    service: "equity_forward_ldn",
    region: "HKG",
    submittedBy: "Niamh Mori",
    canUploadSUD: false,
  },
  {
    id: "7",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "8",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "9",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "10",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "11",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "12",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "13",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "14",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "15",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "16",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "17",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "18",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "19",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
  {
    id: "20",
    date: "15/12/2025 03:17 PM",
    service: "equity_barrier_option",
    region: "HKG",
    submittedBy: "Evelyn Hayes",
    canUploadSUD: false,
  },
];
